name: Lighthouse CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run Lighthouse on"
        required: false
        default: "main"
        type: string

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install ci

      - name: Build application
        run: npm run build

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli
          lhci autorun # saves to .lighthouse/

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results-${{github.event.pull_request.number || github.sha}}
          path: frontend/.lighthouse/
          retention-days: 90
          include-hidden-files: true
